# Header
menu:
  Home: /
  Archives: /archives
  About: /about/
  Find Us: /contact/

# Logo Image Source
logo_src:

# Theme Main Subtitle
subtitle_main: Wherever you might land – we may be there

# Theme Secondary subtitle
subtitle_secondary: We are excited to have been selected to take part in a piece exhibited in the Dutch Pavilion, <a href="https://work-body-leisure.hetnieuweinstituut.nl">WORK, BODY, LEISURE</a> of the 2018 Venice Biennale with the PRIOR ART AUTOMATON.

subtitle_tertiary: We are also exploring data mining, mapping power structures, visualising the law and the relationship possibilities between Artificial Intelligence and the law. So, please,  stay tuned.

# Footer About Section
about_footer:

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: 
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/studio_alight
instagram_url: https://www.instagram.com/studioalight/
github_url: https://github.com/studioalight.com/
email_url: mailto:info@studioalight.com
