# Header
menu:
  Home: /
  Archives: /archives
  About: /about/
  Find Us: /contact/

# Logo Image Source
logo_src:

# Theme Main Subtitle
subtitle_main: Wherever you might land – we may be there

# Theme Secondary subtitle
#subtitle_secondary: It has been a pleasure to have been selected and taken part in a piece exhibited in the Dutch Pavilion, <a href="https://work-body-leisure.hetnieuweinstituut.nl">WORK, BODY, LEISURE</a> of the 2018 Venice Biennale with the PRIOR ART AUTOMATON. Then, after Venice, the exhibition content has traveled through the Autumn 2018 and has been displayed at the V&A in London as part of the London Design Festival and, also, shown at the Het Nieuwe Instituut in Rotterdam. 
subtitle_secondary: Currently we are showing our piece "Choice Bubble" on the <a href="https://wayoutwest.se">Way Out West</a> festival in Gothenburg, 8 - 10 August 2019.

subtitle_tertiary: Concurrently, we are preparing for our upcoming solo exhbition Rob Law at <a href="https://icia.se">ICIA</a>, Ringön Gothenburg in the end of August. Please stay tuned for more details

# Footer About Section
about_footer:

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: 
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/studio_alight
instagram_url: https://www.instagram.com/studioalight/
github_url: https://github.com/studioalight.com/
email_url: mailto:info@studioalight.com
